#Brenna Norton
#I will be creating a game menu
var1 = '*'
print(var1*40)
print(var1+ ('                                      ') + (var1))
print(var1+('            ') +('My Game') + ('                   ') + (var1))
print(var1+('             ') +('Menu') + ('                     ') + (var1))
print(var1+ ('                                      ') + (var1)) 
print(var1+ ('           ') + ('Player 1') + ('                   ') + (var1))
print(var1+ ('   ') + ('Level 1') + ('                            ') + (var1))
print(var1+ ('   ') + ('Level 2')+ ('                            ') + (var1))
print(var1+ ('   ') + ('Level 3')+ ('                            ') + (var1))
print(var1+ ('   ') + ('Level 4')+ ('                            ') + (var1))
print(var1+ ('                                      ') + (var1))
print(var1+ ('                                      ') + (var1))
print(var1+ ('   ') + ('Answer is not 4')+ ('                    ') + (var1))
print(var1+ ('   ') + ('Score=0')+ ('                            ') + (var1))
print(var1+ ('   ') + ('Exit Game')+ ('                          ') + (var1))
print(var1+ ('   ') + ('Goodbye')+ ('                            ') + (var1))
print(var1*40)